### ISSUE TITLE
Add party_wikidata field

### ISSUE THREAD

**Issue by henare** [everypolitician-scrapers/germany-bundestag-19-members-wikipedia#1]
As described here: https://github.com/everypolitician/democratic-commons-tasks/issues/1#issuecomment-345613167

**Comment by henare** [comment]
It turns out adding this is not as simple as we thought on the issue mentioned and linked above. The decorator isn't linking to any specific party Wikidata IDs, just their faction pages, so it's not clear to me how we should add this field.

**Comment by henare** [comment]
I've now seen some Wikidata qualifiers use the faction as the qualifier on their P39 statement so we're back to being able to potentially use it :dizzy:

**Comment by henare** [comment]
Added party_wikidata using the faction Wikidata IDs we were getting in the page (done in quite a painful way in 0afd600).

The [resulting comparison](https://www.wikidata.org/w/index.php?title=User:Henare/prompts/germany-bundestag-19-members-wikipedia/comparison&oldid=597049795) showed that these weren't comparable fields so it's not a useful comparison. Back to square one by the looks of it.

**Comment by tmtmtmtm** [comment]
Woohoo! I think this is a case of you having got to where you needed to be, without quite realising it 😀 

These *are* comparable — and are now highlighting that Wikidata needs to be corrected for most of those people. I'm pretty sure the large number of mismatches come from the data having been added immediately after the election, when the factions hadn't formed yet (the Bundestag didn't have its first sitting until a month after the election.) The P39 data should list the faction, as that's the relevant item for the legislature itself (and is what could vary if someone were to switch faction mid-term). If we also want to store the electoral party, that should be in P3602, such as with https://www.wikidata.org/wiki/Q1666351#P3602

So this is looking good to me now, though I think you could simplify the implementation considerably. There are a couple of possible approaches I'd investigate here (without having looked closely enough at this specific case, so apologies if this turns out to be a bum steer):

My first approach would probably be to see if I could use a decorator to replace the cell that is only a colour with a link to the faction instead. Then, by the time the wikidata decorator runs, there'll be a link there that can be expanded. (The general principle of the decorators are for when you think "Hmmm, this would all be a lot easier if the underlying data were shaped like this instead", so you make that be so before doing the actual scraping part.)

If turns out not to work well, I'd consider making that individual field in turn be a fragment, similarly to how we do things like extracting honorifics from names in scrapers like https://github.com/everypolitician-scrapers/malawi-parliament/blob/master/scraper.rb

Those are just general approaches though, rather than a comment on the code itself. If I get any time later I'll look more deeply at the current implementation, but I'm not sure how likely that will be.

**Comment by henare** [comment]
Thanks @tmtmtmtm :star2: I definitely wouldn't have known this was doing the right thing without your help.

In #2 I decided to decorate `wikidata_party` onto the cell that contains the party. Now that I re-read Tony's comment that's not quite what he was suggesting. On [another comment](https://github.com/everypolitician/democratic-commons-tasks/issues/1#issuecomment-346279111) Tony also suggested renaming `party` to `faction`.

So given that, I think my decorator would be better off adding a new cell that contained the faction name and link so the Wikidata ID decorator can then decorate it and we can extract it like everything else.

**Comment by henare** [comment]
>adding a new cell that contained the faction name

I was thinking this was the right thing to do because the Wikipedia table we're scraping already has `party`. So I was thinking I wanted to preserve that and add faction. However I think we should be replacing the party because Wikipedia is subtly, but importantly, wrong. Tony gave me this explanation in Slack (that I don't think he'll mind me pasting here):

>a parliamentary faction and a coalition are two quite different things
>in countries with strong faction-based systems (such as Germany) you can only sit in Parliament as a member of a faction, not as a party
>those factions can then in turn form coalitions
>in most such countries, where no-one gets a full majority, they usually need to form a coalition to form a government
>but those are coalitions of factions, rather than of parties
>the P4100 for an individual member to should be to their faction, not their party or coaltion

That approach is also closer to what Tony suggested above:

>replace the cell that is only a colour with a link to the faction instead

Except that there isn't a cell that's just a colour. The colour is a border applied to the cell.

So new plan is to replace the contents of the party cell with the faction cell (which links to the faction page and will be decorated by the Wikipedia ID decorator).

**Comment by tmtmtmtm** [comment]
> Wikipedia is subtly, but importantly, wrong

I don't think it is. It's just showing two different things within the same cell. The text is to the party the person was elected as, and the coloured cell is a reference to the faction they're part of. Those are both useful pieces of information.

I've added #3 as an approach to capture both of these, as well as the Wikidata ID for the faction. As there doesn't seem to be anywhere on the page linking to pages for the parties, we can't get the Wikidata IDs for those, but I don't think that's a problem, as we don't really have any need for those at the moment anyway. If anyone else wants to use this scraper later and _does_ need those, we (or they!) can revisit that later.

**Comment by henare** [comment]
It was just me that was _subtly, but importantly, wrong_ :wink:

I'm calling this closed by #3 as we've now got what we need (even if it wasn't a `party_wikidata` field).

Thanks for all your help with this @tmtmtmtm :trophy:
